openapi: "3.1.0"
info:
  title: Knockem
  description: API for submitting tasks to Knockem.
  version: "1.0"

servers:
  - url: '/api/v1'

paths:
  /submissions/:
    post:
      summary: Add a new submission
      operationId: add_submission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - containerEnv
                - containerImage
                - genomeContent
                - maxCompetitionsActive
                - maxCompetitionsFail
                - userEmail
              properties:
                containerEnv:
                  type: object
                  additionalProperties:
                    type: string
                  example: { "ENV_VAR1": "value1", "ENV_VAR2": "value2" }
                containerImage:
                  type: string
                  example:
                    - "yourorg/yourimage:tag"
                    - "ghcr.io:yourorg/yourimage:tag"
                  description: see `spec/containerAPI.md` for details
                genomeContentAlpha:
                  type: string
                  example: |
                    Search
                    Nop-C
                    Nop-D
                    Push-Prev
                    SetMemory
                    Nop-A
                maxCompetitionsActive:
                  type: integer
                  format: int32
                  example: 5
                maxCompetitionsFail:
                  type: integer
                  format: int32
                  example: 3
                userEmail:
                  type: string
                  format: email
                  example: "user@example.com"
      responses:
        200:
          description: Successfully created a new submission
          content:
            application/json:
              schema:
                type: object
                required:
                  - submissionId
                properties:
                  submissionId:
                    type: string
                    example: "550e8400-e29b-41d4-a716-44665544000"
        400:
          description: Invalid input
        500:
          description: Internal server error
